export const SERVER_API_URL = 'http://localhost:8080/api';
export const AUTHENTICATE_URL = SERVER_API_URL + '/authenticate';
export const USER_API_URL = SERVER_API_URL + '/users';
export const SUBSCRIBER_API_URL = SERVER_API_URL + '/subscribers';
export const PUBLICATION_API_URL = SERVER_API_URL + '/publications';
export const CITY_API_URL = SERVER_API_URL + '/cities';
export const SUBSCRIPTION_TYPE_API_URL = SERVER_API_URL + '/subscription-types';
export const SUBSCRIPTION_API_URL = SERVER_API_URL + '/subscriptions';
export const TICKET_API_URL = SERVER_API_URL + '/tickets';
